# Generated by Django 2.1.7 on 2019-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(default='Doge', max_length=50)),
                ('activity_level', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=3)),
                ('coat_length', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=3)),
                ('drools', models.BooleanField(default=True)),
                ('goodChildren', models.BooleanField(default=True)),
                ('grooming', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=3)),
                ('intelligence', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=3)),
                ('shedding', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=3)),
                ('size', models.CharField(choices=[('GIA', 'Giant'), ('LAR', 'Large'), ('MED', 'Medium'), ('SMA', 'Small'), ('MIN', 'Miniature')], default='MED', max_length=3)),
                ('img_path', models.CharField(default='none.jpg', max_length=50)),
            ],
        ),
    ]
