# Generated by Django 2.1.7 on 2019-03-13 20:47

from django.db import migrations, models
import csv 

def create_dogs(apps, schema_editor):

    Dog = apps.get_model('dogs', 'Dog')
    with open('dogsheet.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            d = Dog(
                breed_name = row[0],
                activity_level = fix(row[1]),
                coat_length = fix(row[2]),
                drools = fix(row[3]),
                goodChildren = fix(row[4]),
                grooming = fix(row[5]),
                intelligence = fix(row[6]),
                shedding = fix(row[7]),
                size = fix(row[8]),
                img_path = row[9]
            )
            d.save()

def fix(term):
    value = term.upper()
    if term == 'TRUE' or term == 'FALSE':
        value = value.capitalize()
    else:
        value = value[0:3]
    return value

class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dogs),
    ]
